version: '3.8'

services:
  api:
    build: ./node-api
    ports:
      - "5000:5000"
    depends_on:
      - inference
      - redis

  inference:
    build: ./python-inference
    ports:
      - "6000:6000"

  redis:
    image: redis
    ports:
      - "6379:6379"
